/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_guedesite_desk_Ambilight */

#ifndef _Included_fr_guedesite_desk_Ambilight
#define _Included_fr_guedesite_desk_Ambilight
#ifdef __cplusplus
extern "C" {
#endif
#undef fr_guedesite_desk_Ambilight_MIN_PRIORITY
#define fr_guedesite_desk_Ambilight_MIN_PRIORITY 1L
#undef fr_guedesite_desk_Ambilight_NORM_PRIORITY
#define fr_guedesite_desk_Ambilight_NORM_PRIORITY 5L
#undef fr_guedesite_desk_Ambilight_MAX_PRIORITY
#define fr_guedesite_desk_Ambilight_MAX_PRIORITY 10L
#undef fr_guedesite_desk_Ambilight_MIN_4K_WIDTH
#define fr_guedesite_desk_Ambilight_MIN_4K_WIDTH 1000L
#undef fr_guedesite_desk_Ambilight_MIN_4K_HEIGHT
#define fr_guedesite_desk_Ambilight_MIN_4K_HEIGHT 1000L
/*
 * Class:     fr_guedesite_desk_Ambilight
 * Method:    getScreenPixels
 * Signature: (Ljava/lang/String;IIIF)Lfr/guedesite/desk/Ambilight/PixelResult;
 */
JNIEXPORT jobject JNICALL Java_fr_guedesite_desk_Ambilight_getScreenPixels
  (JNIEnv *, jobject, jstring, jint, jint, jint, jfloat);

/*
 * Class:     fr_guedesite_desk_Ambilight
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_fr_guedesite_desk_Ambilight_freeMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     fr_guedesite_desk_Ambilight
 * Method:    getPixelArray
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_fr_guedesite_desk_Ambilight_getPixelArray
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
